"""Closed, versioned vocabularies shared across domain and API contracts."""

from enum import StrEnum


class PaymentOutcome(StrEnum):
    APPROVED = "APPROVED"
    BUSINESS_DECLINE = "BUSINESS_DECLINE"
    TECHNICAL_ERROR = "TECHNICAL_ERROR"


class BusinessDeclineCode(StrEnum):
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    EXPIRED_CREDENTIAL = "EXPIRED_CREDENTIAL"
    DO_NOT_HONOR = "DO_NOT_HONOR"


class TechnicalErrorCode(StrEnum):
    TOKEN_VALIDATION_FAILED = "TOKEN_VALIDATION_FAILED"
    GATEWAY_TIMEOUT = "GATEWAY_TIMEOUT"
    ISSUER_TIMEOUT = "ISSUER_TIMEOUT"
    NETWORK_ERROR = "NETWORK_ERROR"
    RATE_LIMITED = "RATE_LIMITED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class PaymentMethod(StrEnum):
    CARD = "CARD"
    MOBILE_WALLET = "MOBILE_WALLET"
    TOKENIZED_CARD = "TOKENIZED_CARD"


class Channel(StrEnum):
    MOBILE_APP = "MOBILE_APP"
    WEB = "WEB"
    CARD_PRESENT = "CARD_PRESENT"


class OperationalEventType(StrEnum):
    DEPLOYMENT = "DEPLOYMENT"
    CONFIG_CHANGE = "CONFIG_CHANGE"
    ROLLBACK = "ROLLBACK"


class OperationalStatus(StrEnum):
    STARTED = "STARTED"
    SUCCEEDED = "SUCCEEDED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class ChangeCategory(StrEnum):
    TOKEN_VALIDATION = "TOKEN_VALIDATION"
    TOKEN_CONFIGURATION = "TOKEN_CONFIGURATION"
    TOKEN_KEY_MANAGEMENT = "TOKEN_KEY_MANAGEMENT"
    ROUTING_CONFIGURATION = "ROUTING_CONFIGURATION"
    RELEASE = "RELEASE"


class TelemetryState(StrEnum):
    WARMING_UP = "WARMING_UP"
    HEALTHY = "HEALTHY"
    STALE = "STALE"
    UNKNOWN = "UNKNOWN"


class IncidentLifecycle(StrEnum):
    WARMING_UP = "WARMING_UP"
    HEALTHY = "HEALTHY"
    SUSPECTED = "SUSPECTED"
    OPEN = "OPEN"
    RECOVERY_CANDIDATE = "RECOVERY_CANDIDATE"
    RESOLVED = "RESOLVED"


class IncidentSeverity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class EvidenceCompleteness(StrEnum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    INVALID = "INVALID"


class EvidenceCategory(StrEnum):
    OBSERVED_FACT = "OBSERVED_FACT"
    DERIVED_FINDING = "DERIVED_FINDING"
    MISSING_EVIDENCE = "MISSING_EVIDENCE"
    LIMITATION = "LIMITATION"


class HypothesisRelation(StrEnum):
    SUPPORTING = "SUPPORTING"
    CONTRADICTORY = "CONTRADICTORY"
    MISSING = "MISSING"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class EvidenceTier(StrEnum):
    STRONG_EVIDENCE = "STRONG_EVIDENCE"
    MODERATE_EVIDENCE = "MODERATE_EVIDENCE"
    WEAK_EVIDENCE = "WEAK_EVIDENCE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class HumanReviewStatus(StrEnum):
    UNREVIEWED = "UNREVIEWED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    REJECTED = "REJECTED"
    INCONCLUSIVE = "INCONCLUSIVE"


class ClaimType(StrEnum):
    OBSERVED_FACT = "OBSERVED_FACT"
    DETERMINISTIC_FINDING = "DETERMINISTIC_FINDING"
    COPILOT_INFERENCE = "COPILOT_INFERENCE"
    RUNBOOK_GUIDANCE = "RUNBOOK_GUIDANCE"


class CopilotAssessment(StrEnum):
    SUPPORTED = "SUPPORTED"
    WEAKENED = "WEAKENED"
    CONFLICTING = "CONFLICTING"
    INCONCLUSIVE = "INCONCLUSIVE"


class TemporalScope(StrEnum):
    INCIDENT_SNAPSHOT = "INCIDENT_SNAPSHOT"
    LIVE_STATUS = "LIVE_STATUS"
    HISTORICAL_BASELINE = "HISTORICAL_BASELINE"


class SimulationAction(StrEnum):
    START = "START"
    INJECT_DEPLOYMENT_REGRESSION = "INJECT_DEPLOYMENT_REGRESSION"
    TRIGGER_ROLLBACK_RECOVERY = "TRIGGER_ROLLBACK_RECOVERY"
    STOP = "STOP"
    RESET = "RESET"


class SimulationState(StrEnum):
    STOPPED = "STOPPED"
    PREWARMING = "PREWARMING"
    RUNNING_HEALTHY = "RUNNING_HEALTHY"
    INJECTING = "INJECTING"
    INCIDENT_ACTIVE = "INCIDENT_ACTIVE"
    RECOVERING = "RECOVERING"
    RESETTING = "RESETTING"
    ERROR = "ERROR"


class MetricKey(StrEnum):
    TECHNICAL_ERROR_RATE = "technical_error_rate"
    APPROVAL_RATE = "approval_rate"
    BUSINESS_DECLINE_RATE = "business_decline_rate"
    THROUGHPUT = "throughput"
    AVERAGE_AUTHORIZATION_LATENCY = "average_authorization_latency"
    P95_AUTHORIZATION_LATENCY = "p95_authorization_latency"
